spring:
  datasource:
    url: jdbc:postgresql://dpg-clrv15sm7d1c73f5m130-a.frankfurt-postgres.render.com:5432/editor_kgno
    username: editor_kgno_user
    password: KrrwqL0WBv4b6bYiwiuSQIPai0sFQjja
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      port: 6379
      database: 0
      host: frankfurt-redis.render.com
      timeout: 600000
      user: red-clrul3km7d1c73f5ie6g
      password: UjRl392NIKuiOf8i7TdH4oyNOwUmFKR4
server:
  port: 8081
