spring:
  datasource:
    url: jdbc:postgresql://dpg-clrv15sm7d1c73f5m130-a.frankfurt-postgres.render.com:5432/editor_kgno
    username: editor_kgno_user
    password: KrrwqL0WBv4b6bYiwiuSQIPai0sFQjja
  data:
    redis:
      url: rediss://red-clrul3km7d1c73f5ie6g:UjRl392NIKuiOf8i7TdH4oyNOwUmFKR4@frankfurt-redis.render.com:6379
server:
  port: 8081
